export const SOURCE_ORIGIN = "https://52-prayer-trainning-book.neocities.org";

export type PrayerCategory = "main" | "supplementary";

export type PrayerCatalogEntry = {
  slug: string;
  title: string;
  category: PrayerCategory;
  itemNumber: number | null;
  countsTowardTotal: boolean;
  displayOrder: number;
  sourcePath: string;
  localFile: string;
};

export const PRAYER_CATALOG: PrayerCatalogEntry[] = [
  {
    slug: "dawn",
    title: "하루를 시작하며 드리는 기도",
    category: "main",
    itemNumber: 1,
    countsTowardTotal: true,
    displayOrder: 1,
    sourcePath: "1_Dawn.html",
    localFile: "01-dawn.html",
  },
  {
    slug: "homeland",
    title: "나라를 위한 기도",
    category: "main",
    itemNumber: 2,
    countsTowardTotal: true,
    displayOrder: 2,
    sourcePath: "2_Homeland.html",
    localFile: "02-homeland.html",
  },
  {
    slug: "church",
    title: "교회를 위한 기도",
    category: "main",
    itemNumber: 3,
    countsTowardTotal: true,
    displayOrder: 3,
    sourcePath: "3_Church.html",
    localFile: "03-church.html",
  },
  {
    slug: "pastor",
    title: "담임목사님을 위한 기도",
    category: "main",
    itemNumber: 4,
    countsTowardTotal: true,
    displayOrder: 4,
    sourcePath: "4_Pastor.html",
    localFile: "04-pastor.html",
  },
  {
    slug: "cell-group",
    title: "목장을 위한 기도",
    category: "main",
    itemNumber: 5,
    countsTowardTotal: true,
    displayOrder: 5,
    sourcePath: "5_CellGroup.html",
    localFile: "05-cell-group.html",
  },
  {
    slug: "conceived-believer",
    title: "태신자를 위한 기도",
    category: "main",
    itemNumber: 6,
    countsTowardTotal: true,
    displayOrder: 6,
    sourcePath: "6_Conceived-Believer.html",
    localFile: "06-conceived-believer.html",
  },
  {
    slug: "faculties",
    title: "사람을 위한 기도",
    category: "main",
    itemNumber: 7,
    countsTowardTotal: true,
    displayOrder: 7,
    sourcePath: "7_Faculties.html",
    localFile: "07-faculties.html",
  },
  {
    slug: "home",
    title: "가정을 위한 기도",
    category: "main",
    itemNumber: 8,
    countsTowardTotal: true,
    displayOrder: 8,
    sourcePath: "8_Home.html",
    localFile: "08-home.html",
  },
  {
    slug: "husband",
    title: "남편을 위한 기도",
    category: "main",
    itemNumber: 9,
    countsTowardTotal: true,
    displayOrder: 9,
    sourcePath: "9_Husband.html",
    localFile: "09-husband.html",
  },
  {
    slug: "wife",
    title: "아내를 위한 기도",
    category: "main",
    itemNumber: 10,
    countsTowardTotal: true,
    displayOrder: 10,
    sourcePath: "10_Wife.html",
    localFile: "10-wife.html",
  },
  {
    slug: "parents",
    title: "부모를 위한 기도",
    category: "main",
    itemNumber: 11,
    countsTowardTotal: true,
    displayOrder: 11,
    sourcePath: "11_Parents.html",
    localFile: "11-parents.html",
  },
  {
    slug: "children",
    title: "자녀를 위한 기도",
    category: "main",
    itemNumber: 12,
    countsTowardTotal: true,
    displayOrder: 12,
    sourcePath: "12_Children.html",
    localFile: "12-children.html",
  },
  {
    slug: "personal-1",
    title: "개인기도 1",
    category: "main",
    itemNumber: 13,
    countsTowardTotal: true,
    displayOrder: 13,
    sourcePath: "13_Personal1.html",
    localFile: "13-personal-1.html",
  },
  {
    slug: "personal-2",
    title: "개인기도 2",
    category: "main",
    itemNumber: 14,
    countsTowardTotal: true,
    displayOrder: 14,
    sourcePath: "14_Personal2.html",
    localFile: "14-personal-2.html",
  },
  {
    slug: "repentance",
    title: "회개기도",
    category: "main",
    itemNumber: 15,
    countsTowardTotal: true,
    displayOrder: 15,
    sourcePath: "15_Repentance.html",
    localFile: "15-repentance.html",
  },
  {
    slug: "spiritual-power",
    title: "영적인 힘을 얻기 위한 기도",
    category: "main",
    itemNumber: 16,
    countsTowardTotal: true,
    displayOrder: 16,
    sourcePath: "16_SpiritualPower.html",
    localFile: "16-spiritual-power.html",
  },
  {
    slug: "temptations",
    title: "시험이 있을 때 드리는 기도",
    category: "main",
    itemNumber: 17,
    countsTowardTotal: true,
    displayOrder: 17,
    sourcePath: "17_Temptations.html",
    localFile: "17-temptations.html",
  },
  {
    slug: "tarry",
    title: "기도가 잘 되지 않을 때 드리는 기도",
    category: "main",
    itemNumber: 18,
    countsTowardTotal: true,
    displayOrder: 18,
    sourcePath: "18_Tarry.html",
    localFile: "18-tarry.html",
  },
  {
    slug: "tired",
    title: "삶에 지칠 때 드리는 기도",
    category: "main",
    itemNumber: 19,
    countsTowardTotal: true,
    displayOrder: 19,
    sourcePath: "19_Tired.html",
    localFile: "19-tired.html",
  },
  {
    slug: "thanks",
    title: "감사할 때 드리는 기도",
    category: "main",
    itemNumber: 20,
    countsTowardTotal: true,
    displayOrder: 20,
    sourcePath: "20_Thanks.html",
    localFile: "20-thanks.html",
  },
  {
    slug: "healing",
    title: "몸이 아플 때 드리는 기도",
    category: "main",
    itemNumber: 21,
    countsTowardTotal: true,
    displayOrder: 21,
    sourcePath: "21_Healing.html",
    localFile: "21-healing.html",
  },
  {
    slug: "spouse",
    title: "부부간에 불화가 있을 때 드리는 기도",
    category: "main",
    itemNumber: 22,
    countsTowardTotal: true,
    displayOrder: 22,
    sourcePath: "22_Spouse.html",
    localFile: "22-spouse.html",
  },
  {
    slug: "money",
    title: "물질적인 어려움에 있을 때 드리는 기도",
    category: "main",
    itemNumber: 23,
    countsTowardTotal: true,
    displayOrder: 23,
    sourcePath: "23_Money.html",
    localFile: "23-money.html",
  },
  {
    slug: "business",
    title: "사업을 위한 기도",
    category: "main",
    itemNumber: 24,
    countsTowardTotal: true,
    displayOrder: 24,
    sourcePath: "24_Business.html",
    localFile: "24-business.html",
  },
  {
    slug: "night",
    title: "하루를 마감하며 드리는 기도",
    category: "main",
    itemNumber: 25,
    countsTowardTotal: true,
    displayOrder: 25,
    sourcePath: "25_Night.html",
    localFile: "25-night.html",
  },
  {
    slug: "defeat-devil",
    title: "마귀를 물리치는 기도",
    category: "main",
    itemNumber: 26,
    countsTowardTotal: true,
    displayOrder: 26,
    sourcePath: "26-defeat-devil.txt",
    localFile: "26-defeat-devil.txt",
  },
  {
    slug: "heal-sickness",
    title: "질병을 치료하는 기도",
    category: "main",
    itemNumber: 27,
    countsTowardTotal: true,
    displayOrder: 27,
    sourcePath: "27-heal-sickness.txt",
    localFile: "27-heal-sickness.txt",
  },
  {
    slug: "hope-prayer",
    title: "소원 기도",
    category: "supplementary",
    itemNumber: null,
    countsTowardTotal: false,
    displayOrder: 28,
    sourcePath: "hope_prayer.html",
    localFile: "hope-prayer.html",
  },
  {
    slug: "conceived-prayer",
    title: "태신자 기도",
    category: "supplementary",
    itemNumber: null,
    countsTowardTotal: false,
    displayOrder: 29,
    sourcePath: "Conceived_prayer.html",
    localFile: "conceived-prayer.html",
  },
  {
    slug: "spiritual-prayer",
    title: "영적 대적 기도",
    category: "supplementary",
    itemNumber: null,
    countsTowardTotal: false,
    displayOrder: 30,
    sourcePath: "Spiritual_prayer.html",
    localFile: "spiritual-prayer.html",
  },
];

export const MAIN_PRAYER_COUNT = 27;
export const SUPPLEMENTARY_PRAYER_COUNT = 3;
export const TOTAL_PRAYER_COUNT = MAIN_PRAYER_COUNT + SUPPLEMENTARY_PRAYER_COUNT;
