import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { PRAYER_CATALOG, SOURCE_ORIGIN, type PrayerCatalogEntry } from "../lib/prayers/catalog";
import { htmlToMarkdown } from "../lib/prayers/html-to-markdown";
import { uuidFromSlug } from "../lib/prayers/ids";
import { yamlQuote, type PrayerItemRecord } from "../lib/prayers/markdown";
import { assertValidPrayers } from "../lib/prayers/validate";

const ROOT = process.cwd();
const SOURCE_DIR = path.join(ROOT, "content", "prayers", "source");
const OUTPUT_DIR = path.join(ROOT, "content", "prayers");
const SEED_PATH = path.join(ROOT, "supabase", "seed.sql");

async function main() {
  const useNetwork = process.argv.includes("--from-network");
  const items: PrayerItemRecord[] = [];

  for (const entry of PRAYER_CATALOG) {
    const { contentMd, sourceUrl } = await loadContent(entry, useNetwork);
    if (!contentMd.trim()) {
      throw new Error(`본문을 추출하지 못했습니다: ${entry.slug} (${entry.sourcePath})`);
    }

    items.push({
      id: uuidFromSlug(entry.slug),
      item_number: entry.itemNumber,
      slug: entry.slug,
      title: entry.title,
      content_md: contentMd,
      category: entry.category,
      counts_toward_total: entry.countsTowardTotal,
      display_order: entry.displayOrder,
      source_url: sourceUrl,
      content_version: 1,
      is_active: true,
    });
  }

  assertValidPrayers(items);
  await mkdir(OUTPUT_DIR, { recursive: true });

  for (const item of items) {
    await writeFile(path.join(OUTPUT_DIR, `${item.slug}.md`), toMarkdownFile(item), "utf8");
  }

  await mkdir(path.dirname(SEED_PATH), { recursive: true });
  await writeFile(SEED_PATH, toSeedSql(items), "utf8");

  console.log(`imported ${items.length} prayers`);
  console.log(`main=${items.filter((item) => item.category === "main").length}`);
  console.log(`supplementary=${items.filter((item) => item.category === "supplementary").length}`);
}

async function loadContent(
  entry: PrayerCatalogEntry,
  useNetwork: boolean,
): Promise<{ contentMd: string; sourceUrl: string }> {
  if (entry.localFile.endsWith(".txt")) {
    const localPath = path.join(SOURCE_DIR, entry.localFile);
    const raw = await readFile(localPath, "utf8");
    return {
      contentMd: textSourceToMarkdown(raw, entry.title),
      sourceUrl: `local://${entry.localFile}`,
    };
  }

  const html = await loadHtml(entry, useNetwork);
  const { contentMd } = htmlToMarkdown(html);
  return {
    contentMd,
    sourceUrl: `${SOURCE_ORIGIN}/${entry.sourcePath}`,
  };
}

function textSourceToMarkdown(raw: string, title: string): string {
  const text = raw.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n").trim();
  const lines = text.split("\n");
  if (lines[0]?.trim() === title) {
    return lines.slice(1).join("\n").replace(/^\n+/, "").trim();
  }
  return text;
}

async function loadHtml(entry: PrayerCatalogEntry, useNetwork: boolean): Promise<string> {
  const localPath = path.join(SOURCE_DIR, entry.localFile);

  if (useNetwork) {
    try {
      const response = await fetch(`${SOURCE_ORIGIN}/${entry.sourcePath}`);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const html = await response.text();
      await mkdir(SOURCE_DIR, { recursive: true });
      await writeFile(localPath, html, "utf8");
      return html;
    } catch (error) {
      console.warn(`네트워크에서 ${entry.sourcePath}를 가져오지 못했습니다. 로컬 원본을 사용합니다.`, error);
    }
  }

  try {
    return await readFile(localPath, "utf8");
  } catch {
    throw new Error(
      `원문을 가져오지 못했습니다: ${entry.title} (${entry.sourcePath}). 내용을 추측하지 않습니다.`,
    );
  }
}

function toMarkdownFile(item: PrayerItemRecord): string {
  return [
    "---",
    `id: ${item.id}`,
    `item_number: ${item.item_number ?? "null"}`,
    `slug: ${item.slug}`,
    `title: ${yamlQuote(item.title)}`,
    `category: ${item.category}`,
    `counts_toward_total: ${item.counts_toward_total}`,
    `display_order: ${item.display_order}`,
    `source_url: ${yamlQuote(item.source_url)}`,
    `content_version: ${item.content_version}`,
    `is_active: ${item.is_active}`,
    "---",
    "",
    item.content_md,
    "",
  ].join("\n");
}

function toSeedSql(items: PrayerItemRecord[]): string {
  const values = items
    .map((item) => {
      return `(
  '${item.id}'::uuid,
  ${item.item_number === null ? "NULL" : String(item.item_number)},
  ${sqlString(item.slug)},
  ${sqlString(item.title)},
  ${sqlString(item.content_md)},
  ${sqlString(item.category)},
  ${item.counts_toward_total},
  ${item.display_order},
  ${sqlString(item.source_url)},
  ${item.content_version},
  ${item.is_active}
)`;
    })
    .join(",\n");

  return `-- Generated by scripts/import-prayers.ts
-- Do not edit prayer body text by hand.

insert into public.prayer_items (
  id,
  item_number,
  slug,
  title,
  content_md,
  category,
  counts_toward_total,
  display_order,
  source_url,
  content_version,
  is_active
)
values
${values}
on conflict (id) do update set
  item_number = excluded.item_number,
  slug = excluded.slug,
  title = excluded.title,
  content_md = excluded.content_md,
  category = excluded.category,
  counts_toward_total = excluded.counts_toward_total,
  display_order = excluded.display_order,
  source_url = excluded.source_url,
  content_version = excluded.content_version,
  is_active = excluded.is_active,
  updated_at = now();
`;
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
